settings:

  language: "en"

  admin-perm: "token.admin"

  storage:
    #MONGODB - SQLITE
    type: "SQLITE"
    mongodb:
      url: "mongodb://localhost:27017"
      db: "test"
      collection: "test"
    sql:
      host: "localhost"
      port: 3306
      database: "test"
      user: "root"
      password: "root"