settings:

  language: "en"

  admin-perm: "token.admin"

  storage:
    #MONGODB - SQLITE
    type: "MONGODB"
    mongo:
      url: "mongodb://localhost:27017"
      db: "test"
      collection: "test"